/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Estructuras.Hash;

import Procesamiento.ListaSimpleReportes;
import Procesamiento.MapeadorAminoacidos;
import Procesamiento.NodoReportes;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * Función que muestra un reporte de los aminoácidos
 * @author alexandraloynaz
 */
public class VentanaListaAmino extends javax.swing.JFrame {
    private Hash hashTable;
/**
 * Constructor
 * @param hashTable La hashTable que ya fue comprabada
 */
    public VentanaListaAmino(Hash hashTable) {
       initComponents();
        setSize(600,630);
        this.hashTable = hashTable;
        MapeadorAminoacidos mapeador = new MapeadorAminoacidos();
        ListaSimpleReportes listaAmino = new ListaSimpleReportes();

        listaAmino = mapeador.generarReporteAminoacidos(hashTable);
        NodoReportes actual = listaAmino.getpFirsrt();
        String reporte = "";
            
        while (actual != null) {
        reporte += actual.getDato() + "\n";
    actual = actual.getpNext();
}


        
        AreaMostrar.setText(reporte);
//        AreaMostrar.setText(listaAmino.imprimir());
        ImageIcon BotonRegresar = new ImageIcon(getClass().getResource("/Imagenes/botonRegresar.png"));
        botonRegresar.setIcon(BotonRegresar);
       
        setLocationRelativeTo(null);
        ImageIcon imagenfondo = new ImageIcon(getClass().getResource("/Imagenes/FondoListaAminoacidos.png"));
        JLabel fondo = new JLabel(imagenfondo);
        getContentPane().add(fondo,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 605));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 130, 40));

        AreaMostrar.setColumns(20);
        AreaMostrar.setRows(5);
        jScrollPane1.setViewportView(AreaMostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListaAmino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListaAmino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListaAmino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListaAmino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Hash nulo = new Hash();
                new VentanaListaAmino(nulo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaMostrar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
