/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Estructuras.Hash;
import Procesamiento.ProcesadorADN;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 * Ventana para cargar archivos TXT.
 * Permite: seleccionar un archivo y continuar a la 
 * siguiente ventena.
 * @author alexandraloynaz
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Indica si el archivo fu cargado y validado
     */
    private boolean continuar = false;
     /**
     * Crea la ventana 600X630 px, con sus botones, imagen de fondo y texto
     */
    public Ventana2() {
        initComponents();
        setSize(600,630);
        setLocationRelativeTo(null);

        ImageIcon boton = new ImageIcon(getClass().getResource("/Imagenes/BotonCargarTXT.png"));
        BotonCargarTXT.setIcon(boton);
        ImageIcon imagenFondo= new ImageIcon(getClass().getResource("/Imagenes/FondoVentana2.png"));
        JLabel fondo = new JLabel(imagenFondo);
        getContentPane().add(fondo,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 605));
        TextoAprobacionTXT.setText("");
        ImageIcon continuar = new ImageIcon(getClass().getResource("/Imagenes/BotonContinuar.png"));
        BotonContinuar.setIcon(continuar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonCargarTXT = new javax.swing.JButton();
        TextoAprobacionTXT = new javax.swing.JTextField();
        BotonContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonCargarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargarTXTActionPerformed(evt);
            }
        });
        getContentPane().add(BotonCargarTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 230, 80));

        TextoAprobacionTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoAprobacionTXTActionPerformed(evt);
            }
        });
        getContentPane().add(TextoAprobacionTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 230, -1));

        BotonContinuar.setText("jButton1");
        BotonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoAprobacionTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoAprobacionTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoAprobacionTXTActionPerformed

    private void BotonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonContinuarActionPerformed
         if(continuar){
            Ventana3 v3= new Ventana3(); 
            v3.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Primero debe cargar un archivo TXT y se debe validar que cumpla con la estructura", "Error", JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_BotonContinuarActionPerformed

    private void BotonCargarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargarTXTActionPerformed
        ProcesadorADN procesador = new ProcesadorADN();
        JFileChooser archivo = new JFileChooser();
        archivo.setFileFilter(new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));
        int resultado = archivo.showOpenDialog(this); 
        File archivoSeleccionado = null;
//        if (archivoSeleccionado == null) {
//            JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo.", "Aviso", JOptionPane.WARNING_MESSAGE);
//            return; 
//}
        if(resultado == JFileChooser.APPROVE_OPTION){
           archivoSeleccionado = archivo.getSelectedFile();
        }
        try{
            Hash tableHash = procesador.procesarArchivo(archivoSeleccionado); 
            if(tableHash!= null){
                TextoAprobacionTXT.setText("Archivo cargado con exito");
                continuar = true;
                BotonContinuar.setEnabled(continuar);
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al cargar el archivo, asegura que tenga la estructura deseada", "Error", JOptionPane.ERROR_MESSAGE);
            }
}
        catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error inesperado, vuelva a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
                }
        
    }//GEN-LAST:event_BotonCargarTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCargarTXT;
    private javax.swing.JButton BotonContinuar;
    private javax.swing.JTextField TextoAprobacionTXT;
    // End of variables declaration//GEN-END:variables
}
