/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Estructuras.Hash;
import Estructuras.NodoHash;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author alexandraloynaz
 */
public class VentanaBPatrones extends javax.swing.JFrame {
    private Hash hashTable;
    /**
     * Creates new form VentanaBPatrones
     */
    public VentanaBPatrones(Hash hashTable) {
        initComponents();
        setSize(600,630);
        this.hashTable = hashTable;
        AreaRespuesta.setText("");
        buscarCadena.setText("");
        ImageIcon BotonRegresar = new ImageIcon(getClass().getResource("/Imagenes/botonRegresar.png"));
        botonRegresar.setIcon(BotonRegresar);
        ImageIcon Botonbuscar = new ImageIcon(getClass().getResource("/Imagenes/botonBuscarPatrones.png"));
        botonBuscar.setIcon(Botonbuscar);
        setLocationRelativeTo(null);
        ImageIcon imagenfondo = new ImageIcon(getClass().getResource("/Imagenes/FondoBuscarPatrones.png"));
        JLabel fondo = new JLabel(imagenfondo);
        getContentPane().add(fondo,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 605));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaRespuesta = new javax.swing.JTextArea();
        buscarCadena = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 120, 40));

        AreaRespuesta.setColumns(20);
        AreaRespuesta.setRows(5);
        jScrollPane1.setViewportView(AreaRespuesta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 290, 220));

        buscarCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCadenaActionPerformed(evt);
            }
        });
        getContentPane().add(buscarCadena, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 300, 30));

        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
       this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void buscarCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCadenaActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
      String cadena = buscarCadena.getText().trim().toUpperCase();
      if (cadena.isEmpty()) {
        AreaRespuesta.setText("Por favor ingresa una cadena para buscar.");
        return;
    }
      if(cadena.length()!= 3){
        AreaRespuesta.setText("Ingrese una cadena Valida de solo 3 letras \n(Acuerdate que las letras de la cadena son A,T,G y C)\n");
        return;
    }
     NodoHash resultado = hashTable.buscar(cadena); 
     if (resultado != null) {
        String info = "Cadena: " + resultado.getCadena() + "\nFrecuencia: " + resultado.getFrecuencia() + "\nPosiciones: " + resultado.Getposicion()+ "\n";
        AreaRespuesta.setText(info);
    } else {
        AreaRespuesta.setText("No se encontró la cadena: " + cadena+"\n"+ "Acuerdate que las letras de la cadena son\n A,T,G y C \n");
    }

     
     
      
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBPatrones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBPatrones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBPatrones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBPatrones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Hash hashnulo = new Hash();
                new VentanaBPatrones(hashnulo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaRespuesta;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField buscarCadena;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
