/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author corinalynch
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("agregar numero de arbol");

        jLabel2.setText("jLabel2");

        jButton1.setText("comparar recorrido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Establecer arreglo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar arbol ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
import javax.swing.*;
import java.awt.*;

public class BSTInterface {
    private JFrame frame;
    private JTextField treeInputField;
    private JTextField arrayInputField;
    private JTextArea outputArea;
    
    public BSTInterface() {
        initialize();
    }
    
    private void initialize() {
        // Configuración de la ventana principal
        frame = new JFrame("Comparador de ABB");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(500, 400);
        frame.setLayout(new BorderLayout(10, 10));
        
        // Panel principal con márgenes
        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Panel superior para el árbol
        JPanel treePanel = new JPanel(new BorderLayout(5, 5));
        treePanel.setBorder(BorderFactory.createTitledBorder("Construir Árbol Binario"));
        treeInputField = new JTextField();
        treePanel.add(new JLabel("Ingrese número:"), BorderLayout.WEST);
        treePanel.add(treeInputField, BorderLayout.CENTER);
        
        // Panel central para el arreglo
        JPanel arrayPanel = new JPanel(new BorderLayout(5, 5));
        arrayPanel.setBorder(BorderFactory.createTitledBorder("Arreglo para comparar"));
        arrayInputField = new JTextField();
        arrayPanel.add(new JLabel("Ingrese arreglo (ej: 1,2,3):"), BorderLayout.WEST);
        arrayPanel.add(arrayInputField, BorderLayout.CENTER);
        
        // Área de resultados
        outputArea = new JTextArea();
        outputArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(outputArea);
        scrollPane.setBorder(BorderFactory.createTitledBorder("Resultados"));
        
        // Agregar componentes al panel principal
        mainPanel.add(treePanel, BorderLayout.NORTH);
        mainPanel.add(arrayPanel, BorderLayout.CENTER);
        mainPanel.add(scrollPane, BorderLayout.SOUTH);
        
        frame.add(mainPanel);
        frame.setVisible(true);
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new BSTInterface());
    }
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       JButton addToTreeBtn = new JButton("Agregar al Árbol");
addToTreeBtn.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String input = numberField.getText().trim();
        
        if(input.isEmpty()) {
            JOptionPane.showMessageDialog(frame, 
                "Por favor ingrese un número", 
                "Campo vacío", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int number = Integer.parseInt(input);
            bst.insert(number);
            numberField.setText("");
            outputArea.append("Número " + number + " agregado al árbol\n");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(frame, 
                "Debe ingresar un número entero válido", 
                "Error de formato", 
                JOptionPane.ERROR_MESSAGE);
            numberField.setText("");
        }
    }
});
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JButton setArrayBtn = new JButton("Establecer Arreglo");
setArrayBtn.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        String arrayText = arrayField.getText().trim();
        
        if(arrayText.isEmpty()) {
            JOptionPane.showMessageDialog(frame, 
                "Por favor ingrese números separados por comas", 
                "Campo vacío", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            userArray.clear();
            String[] numbers = arrayText.split(",");
            
            for(String numStr : numbers) {
                int num = Integer.parseInt(numStr.trim());
                userArray.add(num);
            }
            
            outputArea.append("Arreglo establecido: " + userArray + "\n");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(frame, 
                "Formato incorrecto. Use números enteros separados por comas.\nEjemplo: 1,3,5,7", 
                "Error en arreglo", 
                JOptionPane.ERROR_MESSAGE);
            arrayField.setText("");
        }
    }
});
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      JButton compareBtn = new JButton("Comparar Recorridos");
compareBtn.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        if(bst.isEmpty()) {
            JOptionPane.showMessageDialog(frame, 
                "El árbol está vacío", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(userArray.isEmpty()) {
            JOptionPane.showMessageDialog(frame, 
                "No se ha establecido un arreglo para comparar", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        List<Integer> inorder = bst.inorder();
        outputArea.append("--- Resultado ---\n");
        outputArea.append("Recorrido Inorden: " + inorder + "\n");
        outputArea.append("Arreglo usuario: " + userArray + "\n");
        
        if(inorder.equals(userArray)) {
            outputArea.append("RESULTADO: COINCIDEN\n\n");
        } else {
            outputArea.append("RESULTADO: NO COINCIDEN\n\n");
        }
    }
});
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
